"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Webhooks = exports.UserScopes = exports.SudoScopes = exports.OrgScopes = exports.Tokens = exports.Templates = exports.EventType = void 0;
var EventType;
(function (EventType) {
    EventType["USER_CREATED"] = "user.created";
    EventType["USER_UPDATED"] = "user.updated";
    EventType["USER_DELETED"] = "user.deleted";
    EventType["AUTH_REFRESH"] = "auth.refresh";
    EventType["AUTH_LOGIN"] = "auth.login";
    EventType["AUTH_LOGIN_OAUTH"] = "auth.login_oauth";
    EventType["AUTH_LOGIN_BACKUP_CODE"] = "auth.login_backupCode";
    EventType["AUTH_LOGIN_GOOGLE"] = "auth.login_google";
    EventType["AUTH_PASSWORD_CHANGED"] = "auth.password_changed";
    EventType["AUTH_PASSWORD_RESET_REQUESTED"] = "auth.passwordReset";
    EventType["AUTH_APPROVE_LOCATION"] = "auth.approveLocation";
    EventType["ORGANIZATION_CREATED"] = "organization.created";
    EventType["ORGANIZATION_UPDATED"] = "organization.updated";
    EventType["ORGANIZATION_DELETED"] = "organization.deleted";
    EventType["EMAIL_CREATED"] = "email.created";
    EventType["EMAIL_UPDATED"] = "email.updated";
    EventType["EMAIL_DELETED"] = "email.deleted";
    EventType["EMAIL_VERIFIED"] = "email.verified";
    EventType["MEMBERSHIP_CREATED"] = "membership.created";
    EventType["MEMBERSHIP_UPDATED"] = "membership.updated";
    EventType["MEMBERSHIP_DELETED"] = "membership.deleted";
    EventType["BILLING_UPDATED"] = "billing.updated";
    EventType["API_KEY_CREATED"] = "apiKey.created";
    EventType["API_KEY_UPDATED"] = "apiKey.updated";
    EventType["API_KEY_DELETED"] = "apiKey.deleted";
})(EventType = exports.EventType || (exports.EventType = {}));
var Templates;
(function (Templates) {
    Templates["EMAIL_VERIFY"] = "email-verify";
    Templates["PASSWORD_RESET"] = "password-reset";
    Templates["NEW_PASSWORD"] = "new-password";
    Templates["INVITED_TO_TEAM"] = "invited";
    Templates["UNAPPROVED_LOCATION"] = "unapproved-location";
    Templates["CREDITS_NEW_USER"] = "credits-new-user";
    Templates["CREDITS_INVITED_BY"] = "credits-invited-by";
})(Templates = exports.Templates || (exports.Templates = {}));
var Tokens;
(function (Tokens) {
    Tokens["LOGIN"] = "auth";
    Tokens["API_KEY"] = "api-key";
    Tokens["ACCESS_TOKEN"] = "access-token";
    Tokens["TWO_FACTOR"] = "2fa";
    Tokens["REFRESH"] = "refresh";
    Tokens["PASSWORD_RESET"] = "password-reset";
    Tokens["EMAIL_VERIFY"] = "email-verify";
    Tokens["EMAIL_RESEND"] = "email-resend";
    Tokens["APPROVE_LOCATION"] = "approve-location";
    Tokens["COUPON"] = "coupon";
    Tokens["EMAIL_UPDATE"] = "email-update";
    Tokens["CONFIRM_APPOINTMENT"] = "appointment";
})(Tokens = exports.Tokens || (exports.Tokens = {}));
var OrgScopes;
(function (OrgScopes) {
    OrgScopes["READ_ORG"] = "org:read";
    OrgScopes["UPDATE_ORG"] = "org:update";
    OrgScopes["DELETE_ORG"] = "org:delete";
    OrgScopes["READ_ORG_BILLING"] = "org:billing:read";
    OrgScopes["UPDATE_ORG_BILLING"] = "org:billing:update";
    OrgScopes["READ_ORG_INVOICES"] = "org:invoices:read";
    OrgScopes["READ_ORG_SOURCES"] = "org:sources:read";
    OrgScopes["CREATE_ORG_SOURCES"] = "org:sources:create";
    OrgScopes["UPDATE_ORG_SOURCES"] = "org:sources:update";
    OrgScopes["DELETE_ORG_SOURCES"] = "org:sources:delete";
    OrgScopes["READ_ORG_SUBSCRIPTIONS"] = "org:subscriptions:read";
    OrgScopes["UPDATE_ORG_SUBSCRIPTIONS"] = "org:subscriptions:update";
    OrgScopes["CREATE_ORG_SUBSCRIPTIONS"] = "org:subscriptions:create";
    OrgScopes["READ_ORG_PLANS"] = "org:plans:read";
    OrgScopes["READ_ORG_API_KEYS"] = "org:api-key:read";
    OrgScopes["READ_ORG_API_KEY_LOGS"] = "org:api-key-logs:read";
    OrgScopes["UPDATE_ORG_API_KEYS"] = "org:api-key:update";
    OrgScopes["DELETE_ORG_API_KEYS"] = "org:api-key:delete";
    OrgScopes["CREATE_ORG_API_KEYS"] = "org:api-key:create";
    OrgScopes["READ_ORG_DOMAINS"] = "org:domain:read";
    OrgScopes["UPDATE_ORG_DOMAINS"] = "org:domain:update";
    OrgScopes["DELETE_ORG_DOMAINS"] = "org:domain:delete";
    OrgScopes["CREATE_ORG_DOMAINS"] = "org:domain:create";
    OrgScopes["VERIFY_ORG_DOMAINS"] = "org:domain:verify";
    OrgScopes["READ_ORG_WEBHOOKS"] = "org:webhook:read";
    OrgScopes["UPDATE_ORG_WEBHOOKS"] = "org:webhook:update";
    OrgScopes["DELETE_ORG_WEBHOOKS"] = "org:webhook:delete";
    OrgScopes["CREATE_ORG_WEBHOOKS"] = "org:webhook:create";
    OrgScopes["READ_ORG_MEMBERSHIPS"] = "org:membership:read";
    OrgScopes["UPDATE_ORG_MEMBERSHIPS"] = "org:membership:update";
    OrgScopes["DELETE_ORG_MEMBERSHIPS"] = "org:membership:delete";
    OrgScopes["CREATE_ORG_MEMBERSHIPS"] = "org:membership:create";
    OrgScopes["READ_ORG_TRANSACTIONS"] = "org:transactions:read";
    OrgScopes["UPDATE_ORG_TRANSACTIONS"] = "org:transactions:update";
    OrgScopes["DELETE_ORG_TRANSACTIONS"] = "org:transactions:delete";
    OrgScopes["CREATE_ORG_TRANSACTIONS"] = "org:transactions:create";
})(OrgScopes = exports.OrgScopes || (exports.OrgScopes = {}));
var SudoScopes;
(function (SudoScopes) {
    SudoScopes["READ"] = "read";
})(SudoScopes = exports.SudoScopes || (exports.SudoScopes = {}));
var UserScopes;
(function (UserScopes) {
    UserScopes["IMPERSONATE"] = "impersonate";
    UserScopes["READ_USER"] = "user:read";
    UserScopes["UPDATE_USER"] = "user:update";
    UserScopes["CHANGE_PASSWORD"] = "user:change-password";
    UserScopes["DELETE_USER"] = "user:delete";
    UserScopes["READ_USER_MEMBERSHIPS"] = "user:memberships:read";
    UserScopes["DELETE_USER_MEMBERSHIPS"] = "user:memberships:delete";
    UserScopes["UPDATE_USER_MEMBERSHIPS"] = "user:memberships:update";
    UserScopes["ENABLE_USER_2FA"] = "user:2fa:enable";
    UserScopes["DISABLE_USER_2FA"] = "user:2fa:disable";
    UserScopes["READ_USER_BACKUP_CODES"] = "user:backup-codes:read";
    UserScopes["REGENERATE_USER_BACKUP_CODES"] = "user:backup-codes:regenerate";
    UserScopes["CREATE_USER_ACCESS_TOKENS"] = "user:access-tokens:create";
    UserScopes["READ_USER_ACCESS_TOKENS"] = "user:access-tokens:read";
    UserScopes["UPDATE_USER_ACCESS_TOKENS"] = "user:access-tokens:update";
    UserScopes["DELETE_USER_ACCESS_TOKENS"] = "user:access-tokens:delete";
    UserScopes["CREATE_USER_EMAILS"] = "user:emails:create";
    UserScopes["READ_USER_EMAILS"] = "user:emails:read";
    UserScopes["DELETE_USER_EMAILS"] = "user:emails:delete";
    UserScopes["RESEND_USER_EMAIL_VERIFICATION"] = "user:emails:resend-verification";
    UserScopes["CREATE_USER_SESSION"] = "user:sessions:create";
    UserScopes["READ_USER_SESSION"] = "user:sessions:read";
    UserScopes["DELETE_USER_SESSION"] = "user:sessions:delete";
    UserScopes["CREATE_USER_IDENTITY"] = "user:identities:create";
    UserScopes["READ_USER_IDENTITY"] = "user:identities:read";
    UserScopes["DELETE_USER_IDENTITY"] = "user:identities:delete";
})(UserScopes = exports.UserScopes || (exports.UserScopes = {}));
var Webhooks;
(function (Webhooks) {
    Webhooks["ALL_EVENTS"] = "*";
    Webhooks["UPDATE_ORGANIZATION"] = "update-organization";
    Webhooks["DELETE_ORGANIZATION"] = "delete-organization";
    Webhooks["UPDATE_ORGANIZATION_BILLING"] = "update-organization-billing";
    Webhooks["UPDATE_ORGANIZATION_SUBSCRIPTION"] = "update-organization-subscription";
    Webhooks["CREATE_ORGANIZATION_SUBSCRIPTION"] = "create-organization-subscription";
    Webhooks["DELETE_ORGANIZATION_SOURCE"] = "delete-organization-source";
    Webhooks["UPDATE_ORGANIZATION_SOURCE"] = "update-organization-source";
    Webhooks["CREATE_ORGANIZATION_SOURCE"] = "create-organization-source";
    Webhooks["UPDATE_API_KEY"] = "update-api-key";
    Webhooks["CREATE_API_KEY"] = "create-api-key";
    Webhooks["DELETE_API_KEY"] = "delete-api-key";
    Webhooks["UPDATE_DOMAIN"] = "update-domain";
    Webhooks["CREATE_DOMAIN"] = "create-domain";
    Webhooks["DELETE_DOMAIN"] = "delete-domain";
    Webhooks["VERIFY_DOMAIN"] = "verify-domain";
    Webhooks["TEST_WEBHOOK"] = "test-webhook";
    Webhooks["UPDATE_WEBHOOK"] = "update-webhook";
    Webhooks["CREATE_WEBHOOK"] = "create-webhook";
    Webhooks["DELETE_WEBHOOK"] = "delete-webhook";
})(Webhooks = exports.Webhooks || (exports.Webhooks = {}));
//# sourceMappingURL=enum.js.map